[font.normal]
family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
  { key = "n", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "F11", action = "ToggleFullscreen" }
]

[window]
padding.x = 8
padding.y = 8
decorations = "None"
opacity = 0.95

