#!/bin/bash

set -e

echo "#GATO: Preparation"

echo "updating the system"
sudo pacman -Syu
echo "installing things"
sudo pacman -S git fzf wget ripgrep wl-clipboard bash-completion \
  ttf-jetbrains-mono-nerd neovim mise \
  docker docker-compose docker-buildx \
  bluez fprintd power-profiles-daemon \
  lazygit lazydocker
sudo systemctl enable bluetooth
sudo usermod -aG docker $USER

# -----------------------------

echo "#GATO: Copying config files"

BASE_DIR="$(pwd)"
FILES=(.bashrc .inputrc)

for file in "${FILES[@]}"; do
  echo "#GATO: Copying $file"
  SOURCE="$BASE_DIR/$file"
  TARGET="$HOME/$file"
  [ -e "$TARGET" ] && cp "$TARGET" "$TARGET.old"
  cp "$SOURCE" "$TARGET"
  echo "Copied $file to $TARGET"
done

# ----------------------------

echo "#GATO: Configuring git"

git config --global init.defaultBranch main
git config --global pager.branch false
git config --global credential.helper store
git config --global pull.rebase true
git config --global commit.gpgsign true

