#!/bin/bash

set -e

echo "#GATO: Preparation"

echo "updating the system"
sudo pacman -Syu
echo "installing things"
sudo pacman -S git fzf wget ripgrep wl-clipboard bash-completion \
  ttf-jetbrains-mono-nerd neovim mise \
  docker docker-compose docker-buildx \
  bluez fprintd power-profiles-daemon \
  lazygit lazydocker
sudo systemctl enable bluetooth
sudo usermod -aG docker $USER

# -----------------------------

echo "#GATO: Copying .bashrc"

BASE_DIR="$(pwd)"

BASHRC_SOURCE="$BASE_DIR/.bashrc"
BASHRC_TARGET="$HOME/.bashrc"

[ -e "$BASHRC_TARGET" ] && cp "$BASHRC_TARGET" "$BASHRC_TARGET.old"

cp "$BASHRC_SOURCE" "$BASHRC_TARGET"
echo "Copied .bashrc to $BASHRC_TARGET"

# ----------------------------

echo "#GATO: Configuring git"

git config --global init.defaultBranch main
git config --global pager.branch false
git config --global credential.helper store
git config --global pull.rebase true
git config --global commit.gpgsign true

