#!/bin/bash

set -e

BASE_DIR="$(pwd)"
CONFIG_DIR="$HOME/.config"

echo "#GATO: Preparation"

echo "updating the system"
sudo pacman -Syu
echo "installing utilities"
sudo pacman -S git fzf wget ripgrep wl-clipboard bash-completion
echo "installing fonts"
sudo pacman -S ttf-jetbrains-mono-nerd 
echo "install apps"
sudo pacman -S neovim mise
echo "install docker"
sudo pacman -S docker docker-compose docker-buildx
echo "install gnome and tools"
sudo pacman -S gdm gnome
sudo pacman -S bluez fprintd power-profiles-daemon
systemctl enable gdm

# -----------------------------

echo "#GATO: Symlinking config folders"

declare -a SYMLINKS=("nvim" "ghostty")

[ -d "$CONFIG_DIR" ] || mkdir -p "$CONFIG_DIR"

for folder in "${SYMLINKS[@]}"; do
  TARGET="$CONFIG_DIR/$folder"
  SOURCE="$BASE_DIR/$folder"

  if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
    echo "Skipping $TARGET (already exists)"
  else
    ln -s "$SOURCE" "$TARGET"
    echo "Symlinked $SOURCE -> $TARGET"
  fi
done

# -----------------------------

echo "#GATO: Copying .bashrc"

BASHRC_SOURCE="$BASE_DIR/.bashrc"
BASHRC_TARGET="$HOME/.bashrc"

[ -e "$BASHRC_TARGET" ] && cp "$BASHRC_TARGET" "$BASHRC_TARGET.old"

cp "$BASHRC_SOURCE" "$BASHRC_TARGET"
echo "Copied .bashrc to $BASHRC_TARGET"

# ----------------------------

echo "#GATO: Configuring git"

git config --global init.defaultBranch main
git config --global pager.branch false
git config --global credential.helper store
git config --global pull.rebase true
git config --global commit.gpgsign true

