#!/bin/bash

link_config() {
  local config_name="$1"
  local config_path="$(pwd)/$config_name"
  local target_dir="$HOME/.config/$config_name"

  if [ -d "$target_dir" ]; then
    echo "skipping $config_name, already exists"
  else
    echo "linking $config_name"
    ln -s "$config_path" "$HOME/.config"
  fi
}

echo "setting up configuration files for nvim, tmux (and tmux plugin manager), and alacritty"
echo "... make sure to install them separately"

link_config "nvim"
link_config "tmux"
link_config "alacritty"

echo "setup complete"
